# properties文件转yaml文件 https://toyaml.com/
server:
  servlet:
    context-path: /gateway
spring:
  application:
    name: train-ticket-gateway
  profiles:
    active: dev
# gateway输出请求日志要增加jvm参数 -Dreactor.netty.http.server.accessLogEnabled=true
  cloud:
    gateway:
      routes:
        - id: member
#          uri: lb://train-ticket-member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
#          uri: lb://train-ticket-business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
        - id: batch
#          uri: lb://train-ticket-batch
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/batch/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: # 允许哪些网站的跨域请求 allowedOrigins: “*” 允许所有网站
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
