server:
  port: 8002
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/train_ticket_business?stringtype=unspecified&timezone=Asia/Shanghai
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: hikariBusiness
      auto-commit: on
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 300000
      connection-test-query: select 1
      validation-timeout: 1500
      minimum-idle: 2
      maximum-pool-size: 10
      schema: public
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 30000ms
      connectTimeout: PT1m
      clientName: redisClient
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
        shutdown-timeout: 100ms
#      cluster:
#        nodes:
#      sentinel:
#        master:
#        nodes:
#      ssl:
#        enabled:

