
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: on
  main:
    banner-mode: log
  jackson:
    time-zone: GMT+9
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: false
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss


management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full

#mybatis-plus:
#  configuration:
#    # 全局启用或禁用延迟加载
#    lazy-loading-enabled: on
#    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
#    aggressive-lazy-loading: off
#    # 是否可以使用列的别名
#    use-column-label: on
#    # 当查询数据为空时字段返回为null，不设置这个字段为true的话查询的数据为null时，字段将被隐藏
#    call-setters-on-nulls: on
#    local-cache-scope: statement
#  global-config:
#    db-config:
#      logic-delete-value: -1
#      logic-not-delete-value: 0
#      logic-delete-field: deleted
#    banner: off
#mybatis-mate:
#  cert:
#    # 请添加微信wx153666购买授权，不白嫖从我做起！ 测试证书会失效，请勿正式环境使用
#    grant: MM20221018001
#    license: TQGrz624uzhq8g3hF2NQTjPiQ3NV3KGTZ56o6D5LKq/w0797fIbeKbPdYMjjYhYybKgfuKnfXaAC//GbCtk+mgbwNtsGVm+chg1kvKV1Qtxc+/X4h9aRIBsrwDUkNWQuwt7ZHIiMkDWOAB2vq2oIPNCkAbQx4J+4E1FhlASbHdIQYmFVvVsQPR8uIXAkDaesxdUdzUaeNV0QezJ6b9lHPW4EUHjExFezYM4dB0LC195RdO0pfSHJGjq8Lq0dm5m9i7JAvVZGuewIPA0XncuEdL5cfzsmy+apz3QJXrv2A30Mu6pASZL+KHr92z1kFsg06zqlI5FI6GHYZuBFd9Vang==
